apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-node-app"
  annotations:
    backstage.io/kubernetes-label-selector: 'app=httpbin'
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
